# -*- coding: utf-8 -*-
"""Contenido de ayuda de cada plantilla Excel: recomendaciones, preguntas frecuentes, glosario y checklist.
La clave es el título que recibe instrucciones() en generar_plantillas.py."""

GENERALES_FAQ = [
    ("¿Por qué no puedo escribir en algunas celdas?",
     "La hoja está protegida para que no se borren fórmulas por accidente. Solo se editan las celdas de captura (color crema). "
     "Si necesitas modificar algo más: pestaña Revisar > Desproteger hoja (no tiene contraseña)."),
    ("¿Cómo agrego mi logotipo?",
     "Haz clic en el recuadro punteado de la esquina superior derecha del formato y usa Insertar > Imágenes. Ajusta el tamaño sin salirte del recuadro."),
    ("¿Cómo lo imprimo o lo convierto a PDF?",
     "Archivo > Imprimir (ya está ajustado a una hoja de ancho). Para PDF elige 'Microsoft Print to PDF' o Archivo > Exportar > PDF."),
    ("¿Con qué versiones de Excel funciona?",
     "Excel 2016, 2019, 2021 y Microsoft 365 (Windows y Mac). Funciona en LibreOffice y Google Sheets, aunque algunas gráficas y formatos pueden verse distintos."),
    ("¿Por qué la letra se ve diferente?",
     "El diseño usa la fuente Abadi, incluida en Microsoft 365. Si tu versión no la tiene, Excel la sustituye por otra; no afecta el funcionamiento."),
    ("¿Puedo usarlo en varias empresas o por varios años?",
     "Sí. Guarda una copia del archivo por empresa o por periodo (Archivo > Guardar como) y deja el original en blanco como plantilla maestra."),
]

CONTENIDO = {
    "Control de ingresos y gastos": {
        "tips": [
            "Registra los movimientos el mismo día; las categorías claras hacen que el Resumen sea útil.",
            "Edita las categorías y los métodos de pago en la hoja CATÁLOGOS: las listas desplegables se actualizan solas.",
            "Concilia el saldo final contra tu estado de cuenta al cierre de cada mes.",
            "Guarda un archivo por mes o por año fiscal y conserva el original en blanco.",
        ],
        "faq": [("¿Qué hago si un movimiento es ingreso y gasto a la vez?", "Captúralos en dos renglones: uno en Ingreso y otro en Gasto, con el mismo concepto."),
                ("¿Cómo agrego una categoría nueva?", "En la hoja CATÁLOGOS escribe la categoría en la primera celda libre de la columna correspondiente.")],
        "glosario": [("INGRESO", "Dinero que entra al negocio por ventas, servicios u otras fuentes."),
                     ("GASTO", "Dinero que sale para operar el negocio."),
                     ("SALDO INICIAL", "Efectivo disponible al comenzar el periodo."),
                     ("SALDO FINAL", "Saldo inicial + ingresos - gastos.")],
        "checklist": ["Todos los movimientos del mes están capturados", "Cada gasto tiene su comprobante (factura o ticket)",
                      "El saldo final coincide con el estado de cuenta", "Se revisó el Resumen y se detectaron categorías anormales"],
    },
    "Control de caja chica": {
        "tips": ["Define un fondo fijo y un responsable único; nunca mezcles dinero personal.",
                 "Todo gasto debe tener vale firmado y comprobante; sin comprobante no se reembolsa.",
                 "Haz arqueo sorpresa al menos una vez al mes; la diferencia debe ser cero.",
                 "Reembolsa el fondo cuando llegue al 30% o menos del monto original."],
        "faq": [("¿Cuánto debe ser el fondo fijo?", "Lo suficiente para cubrir de una a dos semanas de gastos menores. Lo más común es entre $1,500 y $5,000 MXN."),
                ("¿El IVA siempre es 16%?", "En la zona fronteriza puede ser 8%. Si un gasto no genera IVA acreditable, sobrescribe la celda de IVA con 0.")],
        "glosario": [("FONDO FIJO", "Monto asignado a caja chica que se repone periódicamente."), ("VALE", "Comprobante interno firmado por quien recibe el dinero."),
                     ("ARQUEO", "Conteo físico del efectivo y comprobantes para comparar con el fondo."), ("REEMBOLSO", "Reposición del efectivo gastado.")],
        "checklist": ["Fondo fijo autorizado por escrito", "Vales numerados y firmados", "Arqueo realizado y firmado", "Comprobantes entregados a contabilidad"],
    },
    "Flujo de efectivo anual": {
        "tips": ["Captura primero la proyección del año y después compárala mes a mes con lo real.",
                 "Un flujo neto negativo sostenido es señal para renegociar plazos con proveedores o acelerar la cobranza.",
                 "Considera los meses de pago de impuestos, aguinaldo y vacaciones: concentran salidas importantes.",
                 "Revisa el saldo acumulado: debe mantenerse positivo todo el año."],
        "faq": [("¿Debo incluir el IVA?", "Sí, el flujo de efectivo refleja el dinero real que entra y sale, con impuestos incluidos."),
                ("¿Puedo cambiar los conceptos?", "Sí, edita los nombres de la columna A; las fórmulas no se alteran.")],
        "glosario": [("FLUJO NETO", "Ingresos del mes - egresos del mes."), ("SALDO ACUMULADO", "Saldo inicial + suma de flujos netos hasta el mes."),
                     ("LIQUIDEZ", "Capacidad de pagar obligaciones de corto plazo.")],
        "checklist": ["Saldo inicial capturado", "Ingresos esperados por mes capturados", "Egresos fijos y variables capturados", "Se revisó el mes con menor saldo"],
    },
    "Cuentas por cobrar": {
        "tips": ["Revisa el reporte de antigüedad cada semana y llama primero a los saldos más grandes.",
                 "Define políticas de crédito por cliente (días y límite) en el Directorio de clientes.",
                 "Envía recordatorio 3 días antes del vencimiento y otro al día siguiente.",
                 "Un saldo mayor a 90 días suele requerir gestión especial o reserva contable."],
        "faq": [("¿Cómo registro un pago parcial?", "Escribe el acumulado de pagos en la columna Abonos; el saldo se recalcula."),
                ("¿Qué fecha de corte uso?", "Por defecto HOY(); puedes escribir una fecha fija para reportes al cierre de mes.")],
        "glosario": [("ANTIGÜEDAD DE SALDOS", "Clasificación de la deuda según los días de atraso."), ("SALDO VENCIDO", "Importe cuyo plazo de pago ya terminó."),
                     ("DÍAS DE CRÉDITO", "Plazo que se concede al cliente para pagar.")],
        "checklist": ["Facturas del periodo capturadas", "Abonos aplicados", "Recordatorios enviados", "Saldos > 60 días con plan de acción"],
    },
    "Conciliación bancaria": {
        "tips": ["Concilia cada mes con el estado de cuenta del banco, sin importar si hubo pocos movimientos.",
                 "Captura en PARTIDAS cada depósito y cheque en tránsito; el formato suma solo.",
                 "Una diferencia distinta de cero casi siempre es una comisión no registrada o un error de captura.",
                 "Los cheques en tránsito con más de 90 días deben cancelarse o reexpedirse."],
        "faq": [("¿Qué es una partida en tránsito?", "Un movimiento registrado en tus libros que el banco aún no refleja (por ejemplo, un cheque que no se ha cobrado)."),
                ("¿Qué hago si la diferencia no es cero?", "Revisa que no falten comisiones, intereses o IVA bancarios por registrar y que ningún movimiento esté duplicado.")],
        "glosario": [("SALDO SEGÚN BANCO", "Saldo final del estado de cuenta."), ("SALDO SEGÚN LIBROS", "Saldo de tu contabilidad en la cuenta de bancos."),
                     ("DEPÓSITO EN TRÁNSITO", "Depósito en libros que el banco aún no abona."), ("CHEQUE EN TRÁNSITO", "Cheque emitido que aún no se cobra.")],
        "checklist": ["Estado de cuenta del mes descargado", "Saldos capturados", "Partidas en tránsito listadas", "Diferencia en cero y firmada"],
    },
    "Control de asistencia": {
        "tips": ["Llena el control a diario; los registros hechos al final del mes pierden precisión.",
                 "Usa las claves A, F, R, V, I, D y P de forma uniforme para que los conteos sean correctos.",
                 "Tres retardos pueden equivaler a una falta según tu reglamento interior; defínelo por escrito.",
                 "Conserva los controles firmados por al menos 2 años."],
        "faq": [("¿Cómo agrego más empleados?", "El formato incluye 50 renglones. Para más empleados duplica la hoja o usa un archivo adicional."),
                ("¿Se descuentan los días de descanso?", "No, la clave D no cuenta como falta ni como asistencia efectiva en los totales de faltas.")],
        "glosario": [("A", "Asistencia"), ("F", "Falta injustificada"), ("R", "Retardo"), ("V", "Vacaciones"), ("I", "Incapacidad"), ("D", "Descanso"), ("P", "Permiso")],
        "checklist": ["Plantilla de empleados actualizada", "Todos los días capturados", "Faltas y retardos justificados o aplicados", "Totales enviados a nómina"],
    },
    "Nómina simplificada": {
        "tips": ["Este formato sirve para control interno y estimaciones; el cálculo oficial debe hacerse con tablas vigentes del SAT e IMSS.",
                 "Captura el ISR retenido que te arroje tu sistema de nómina o tu contador.",
                 "Las horas extra dobles tienen un límite semanal; verifica la LFT antes de pagar.",
                 "Guarda un archivo por periodo (semana, quincena o mes)."],
        "faq": [("¿El % de IMSS es exacto?", "No. Es una referencia editable; la cuota real varía por ramo, salario base de cotización y prima de riesgo."),
                ("¿Sirve para timbrar recibos?", "No. Para recibos CFDI de nómina usa tu sistema de timbrado.")],
        "glosario": [("SUELDO DIARIO", "Pago por día laborado."), ("SDI", "Salario diario integrado, base de cotización al IMSS."),
                     ("PERCEPCIONES", "Sueldos, horas extra, bonos y demás pagos."), ("DEDUCCIONES", "ISR, IMSS y otros descuentos."), ("NETO", "Percepciones - deducciones.")],
        "checklist": ["Asistencia del periodo validada", "Horas extra autorizadas", "ISR/IMSS calculados", "Dispersión y recibos entregados"],
    },
    "Control de vacaciones": {
        "tips": ["Los días corresponden por años cumplidos según la LFT vigente (reforma 'Vacaciones Dignas', 2023).",
                 "La prima vacacional mínima es 25% sobre los salarios de los días de vacaciones.",
                 "Las vacaciones deben disfrutarse dentro de los 6 meses siguientes al cumplir el año de servicio.",
                 "Revisa tu contrato colectivo: puede otorgar más días que la ley."],
        "faq": [("¿Cuántos días me corresponden al primer año?", "12 días laborables. Cada año aumentan 2 días hasta el cuarto año; después, 2 días cada 5 años."),
                ("¿Se pagan los días no gozados?", "No se pueden cambiar por dinero mientras continúe la relación laboral; solo se pagan en el finiquito.")],
        "glosario": [("ANTIGÜEDAD", "Años completos de servicio."), ("PRIMA VACACIONAL", "Pago adicional del 25% sobre los días de vacaciones."), ("DÍAS PENDIENTES", "Días correspondientes - días tomados.")],
        "checklist": ["Fechas de ingreso verificadas", "Días tomados actualizados", "Solicitudes firmadas archivadas", "Prima vacacional programada en nómina"],
    },
    "Evaluación de desempeño": {
        "tips": ["Evalúa con hechos y ejemplos, no con impresiones; anota evidencia en la columna de comentarios.",
                 "Comparte los criterios con el empleado al inicio del periodo.",
                 "Realiza la entrevista de retroalimentación dentro de la semana siguiente a la evaluación.",
                 "Los pesos de los criterios deben sumar 100%."],
        "faq": [("¿Puedo cambiar los criterios?", "Sí, edita el nombre y el peso; verifica que el total sea 100%."),
                ("¿Qué hago con una calificación baja?", "Acuerda un plan de acción con metas medibles y fecha de revisión.")],
        "glosario": [("PONDERADO", "Calificación x peso del criterio."), ("SOBRESALIENTE", "Resultado >= 4.5"), ("SATISFACTORIO", "Resultado >= 3.5"),
                     ("REQUIERE MEJORA", "Resultado >= 2.5"), ("DEFICIENTE", "Resultado < 2.5")],
        "checklist": ["Criterios acordados con el empleado", "Evaluación llenada con evidencias", "Retroalimentación realizada", "Plan de acción firmado"],
    },
    "Control de inventario": {
        "tips": ["Define un stock mínimo por producto basado en el consumo y el tiempo de entrega del proveedor.",
                 "Haz conteos cíclicos (ABC): los productos de mayor valor se cuentan con más frecuencia.",
                 "Registra entradas y salidas con documento de respaldo.",
                 "Revisa semanalmente los productos en REABASTECER y SIN STOCK."],
        "faq": [("¿Cómo corrijo diferencias de inventario?", "Ajusta con una entrada o salida por ajuste y anota el motivo en tu bitácora."),
                ("¿Puedo manejar varias bodegas?", "Usa una copia del archivo por bodega o agrega la bodega en la categoría.")],
        "glosario": [("EXISTENCIA", "Inventario inicial + entradas - salidas."), ("STOCK MÍNIMO", "Nivel que dispara una nueva compra."), ("SKU", "Código único de cada producto."),
                     ("VALOR DE INVENTARIO", "Existencia x costo unitario.")],
        "checklist": ["Conteo físico realizado", "Entradas y salidas capturadas", "Diferencias analizadas", "Compras sugeridas generadas"],
    },
    "Kardex": {
        "tips": ["Un kardex por artículo; guarda cada uno en una hoja o archivo distinto.",
                 "Las salidas se valúan al costo promedio vigente: no captures costo en las salidas.",
                 "Registra los movimientos en orden cronológico.",
                 "Concilia el saldo final contra el conteo físico."],
        "faq": [("¿Qué es el costo promedio?", "Importe total del inventario dividido entre las unidades; se recalcula con cada entrada."),
                ("¿Sirve para PEPS?", "No, este formato usa costo promedio ponderado.")],
        "glosario": [("COSTO PROMEDIO", "Valor total / unidades disponibles."), ("ENTRADA", "Compra, devolución de cliente o ajuste positivo."), ("SALIDA", "Venta, consumo, merma o ajuste negativo.")],
        "checklist": ["Documentos de entrada y salida capturados", "Saldos coinciden con conteo físico", "Ajustes autorizados"],
    },
    "Orden de compra": {
        "tips": ["Emite la orden antes de recibir el producto, nunca después.",
                 "Anota condiciones de pago y fecha de entrega para dar seguimiento.",
                 "Obtén firma de autorización cuando el monto lo requiera.",
                 "Compara contra la factura del proveedor y la entrada de almacén antes de pagar (conciliación de 3 vías)."],
        "faq": [("¿Cómo numero las órdenes?", "Usa consecutivos por año, por ejemplo OC-2026-001."), ("¿Puedo agregar más partidas?", "El formato trae 15; para más duplica la hoja y numera 'hoja 2 de 2'.")],
        "glosario": [("OC", "Orden de compra."), ("PARTIDA", "Renglón de producto o servicio."), ("CONDICIONES DE PAGO", "Plazo y forma de pago acordados.")],
        "checklist": ["Proveedor autorizado", "Precios confirmados por escrito", "Autorización firmada", "Orden enviada al proveedor"],
    },
    "Cuadro comparativo": {
        "tips": ["Solicita al menos tres cotizaciones con las mismas especificaciones.",
                 "El precio no es el único criterio: valora calidad, garantía, tiempo de entrega y crédito.",
                 "Si un proveedor no cotiza todas las partidas, no es comparable en el total.",
                 "Archiva el cuadro como soporte de la decisión de compra."],
        "faq": [("¿Cuántos proveedores puedo comparar?", "Hasta cuatro."), ("¿Cómo decido si el más barato no es el mejor?", "Anota la justificación y adjunta la autorización del responsable.")],
        "glosario": [("COTIZACIÓN", "Oferta formal de precio por parte de un proveedor."), ("REQUISICIÓN", "Solicitud interna de compra."), ("CONDICIONES COMERCIALES", "Crédito, garantía y entrega.")],
        "checklist": ["Requisición autorizada", "Cotizaciones recibidas con la misma especificación", "Cuadro llenado y firmado", "Proveedor seleccionado notificado"],
    },
    "Cotización": {
        "tips": ["Incluye alcance, exclusiones, vigencia y forma de pago para evitar malentendidos.",
                 "Numera tus cotizaciones con consecutivo y fecha.",
                 "Envía en PDF y da seguimiento a los 3 y 7 días.",
                 "Si el cliente acepta, solicita su firma o una orden de compra."],
        "faq": [("¿Cuál es la vigencia normal?", "Entre 15 y 30 días, según la volatilidad de tus costos."), ("¿Cómo agrego un descuento?", "Escribe el importe en la celda Descuento; el IVA se calcula sobre el subtotal neto.")],
        "glosario": [("SUBTOTAL", "Suma de partidas antes de impuestos."), ("IVA", "Impuesto al Valor Agregado, 16% en la mayor parte del país."), ("VIGENCIA", "Periodo durante el cual los precios son válidos.")],
        "checklist": ["Datos del cliente correctos", "Alcance y exclusiones definidos", "Condiciones comerciales completas", "Enviada y con fecha de seguimiento"],
    },
    "Recibo de pago": {
        "tips": ["Entrega un original al cliente y conserva copia firmada.",
                 "Escribe la cantidad con letra para evitar alteraciones.",
                 "En pagos parciales registra el saldo pendiente.",
                 "El recibo no sustituye a la factura (CFDI) cuando el pago lo requiere."],
        "faq": [("¿Es válido fiscalmente?", "Es un comprobante interno de pago; para deducir se necesita CFDI."), ("¿Cómo numero los recibos?", "Con folio consecutivo por año.")],
        "glosario": [("BUENO POR", "Importe del recibo."), ("ABONO", "Pago parcial."), ("SALDO PENDIENTE", "Lo que aún se debe después del pago.")],
        "checklist": ["Datos del pagador completos", "Cantidad con letra", "Forma de pago y referencia", "Firma de quien recibe"],
    },
    "Minuta de reunión": {
        "tips": ["Envía la minuta dentro de las 24 horas posteriores a la reunión.",
                 "Todo compromiso necesita responsable y fecha límite.",
                 "Da seguimiento a los pendientes al inicio de la siguiente reunión.",
                 "Mantén los acuerdos redactados en forma clara y medible."],
        "faq": [("¿Cuánto debe durar una minuta?", "Una o dos páginas; registra decisiones, no cada comentario."), ("¿Debe firmarse?", "Es recomendable en reuniones de comité, juntas con clientes o asuntos legales.")],
        "glosario": [("ORDEN DEL DÍA", "Temas a tratar."), ("ACUERDO", "Decisión tomada en la reunión."), ("COMPROMISO", "Actividad asignada con responsable y fecha.")],
        "checklist": ["Asistentes registrados", "Acuerdos redactados", "Compromisos con responsable y fecha", "Minuta enviada a todos"],
    },
    "Solicitud de vacaciones o permiso": {
        "tips": ["Presenta la solicitud con anticipación (por ejemplo, 15 días para vacaciones).",
                 "El jefe inmediato valida cobertura de actividades antes de autorizar.",
                 "RH actualiza el saldo de vacaciones después de la autorización.",
                 "Archiva el original en el expediente del empleado."],
        "faq": [("¿Los días hábiles descuentan festivos?", "No; el cálculo es de lunes a viernes. Resta manualmente los festivos."), ("¿Puede rechazarse?", "Sí, por necesidades del servicio, siempre con motivo claro.")],
        "glosario": [("PERMISO CON GOCE", "Se paga el día aunque no se labore."), ("PERMISO SIN GOCE", "No se paga el día."), ("DÍA ECONÓMICO", "Día de permiso otorgado por política interna.")],
        "checklist": ["Datos y fechas completos", "Firma del jefe inmediato", "Firma de RH", "Saldo de vacaciones actualizado"],
    },
    "Presupuesto anual": {
        "tips": ["Parte de los resultados del año anterior y ajusta por inflación y metas de ventas.",
                 "Revisa la variación cada mes y toma acciones si pasa del 10%.",
                 "Separa gastos fijos y variables para identificar dónde puedes ahorrar.",
                 "Actualiza la proyección trimestralmente (reforecast)."],
        "faq": [("¿Cómo leo la variación?", "Real - Presupuesto. En gastos, positiva significa que te pasaste; en ventas, positiva es favorable."), ("¿Puedo agregar conceptos?", "Cambia el nombre de uno de los 10 conceptos disponibles.")],
        "glosario": [("PRESUPUESTO", "Plan de ingresos y gastos."), ("VARIACIÓN", "Diferencia entre lo real y lo presupuestado."), ("% DE EJECUCIÓN", "Real / presupuesto.")],
        "checklist": ["Presupuesto aprobado", "Real capturado al cierre de cada mes", "Variaciones >10% explicadas", "Reforecast trimestral"],
    },
    "Activos fijos": {
        "tips": ["Etiqueta físicamente cada activo con su código.",
                 "Realiza inventario físico de activos al menos una vez al año.",
                 "Registra bajas y ventas con fecha y documento.",
                 "Las tasas de la hoja TASAS son una referencia; confirma con tu contador."],
        "faq": [("¿Qué es el MOI?", "Monto original de la inversión: costo de adquisición sin IVA más gastos de instalación."), ("¿Cómo doy de baja un activo?", "Escribe la fecha de baja en tu bitácora y retira el renglón o márcalo en Ubicación.")],
        "glosario": [("MOI", "Monto original de la inversión."), ("DEPRECIACIÓN", "Pérdida de valor por uso o paso del tiempo."), ("VALOR EN LIBROS", "MOI - depreciación acumulada.")],
        "checklist": ["Activo etiquetado", "Factura archivada", "Responsable asignado", "Inventario físico anual realizado"],
    },
    "Directorio": {
        "tips": ["Captura RFC y razón social tal como aparecen en la constancia de situación fiscal.",
                 "Asigna días y límite de crédito antes de vender a crédito.",
                 "Protege este archivo: contiene datos personales (LFPDPPP).",
                 "Actualiza contactos al menos cada año."],
        "faq": [("¿Cómo filtro solo proveedores?", "Usa el filtro del encabezado de la columna TIPO."), ("¿Cuántos registros caben?", "300; duplica la hoja para más.")],
        "glosario": [("RFC", "Registro Federal de Contribuyentes."), ("RAZÓN SOCIAL", "Nombre legal de la empresa."), ("LÍMITE DE CRÉDITO", "Monto máximo que se puede adeudar.")],
        "checklist": ["Constancia fiscal archivada", "Condiciones de crédito autorizadas", "Datos de contacto verificados"],
    },
}
